# Generated by Django 4.2.13 on 2024-06-10 08:47

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    # forwards_func(): add trailing newline from Lock.certificate,
    # save won't run cleanup_certificate() during migration so we alter it manually
    Lock = apps.get_model("doorlockdb", "Lock")
    db_alias = schema_editor.connection.alias

    for lock in Lock.objects.using(db_alias).all():
        lock.certificate = lock.certificate + "\n"
        lock.save()


def reverse_func(apps, schema_editor):
    # reverse_func(): remove trailing newline from Lock.certificate,
    # save won't run cleanup_certificate() during migration so we alter it manually
    Lock = apps.get_model("doorlockdb", "Lock")
    db_alias = schema_editor.connection.alias

    for lock in Lock.objects.using(db_alias).all():
        lock.certificate = lock.certificate.strip()
        lock.save()


class Migration(migrations.Migration):

    dependencies = [
        ("doorlockdb", "0016_alter_synclockkey_synchronized"),
    ]

    operations = [
        migrations.AlterField(
            model_name="key",
            name="description",
            field=models.CharField(
                help_text='Enter a meaningful description. example="NS OV chipkaart t.h.t. 02-2027"',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="lock",
            name="certificate",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Paste client certitificate here (including '-----BEGIN CERTIFICATE-----' and '-----END CERTIFICATE-----').<br>\n<br>\nOn the client configure this server server Fingerprint. (hint: restart django after server ssl certificate is changed). <br>\n<code> ... This not visible during migrations.\n.</code>",
                max_length=2000,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
