# Generated by Django 4.2.13 on 2024-10-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doorlockdb", "0017_alter_key_description_alter_lock_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="logunknownkey",
            name="meta_data_json",
            field=models.TextField(default="{}"),
        ),
        migrations.AlterField(
            model_name="accessrule",
            name="weekdays_friday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accessrule",
            name="weekdays_monday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accessrule",
            name="weekdays_saturday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accessrule",
            name="weekdays_sunday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accessrule",
            name="weekdays_thursday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accessrule",
            name="weekdays_tuesday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accessrule",
            name="weekdays_wednesday",
            field=models.BooleanField(default=False),
        ),
    ]
