# Generated by Django 4.2.13 on 2024-11-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doorlockdb", "0018_logunknownkey_meta_data_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="key",
            name="meta_data_json",
            field=models.TextField(default="{}"),
        ),
    ]
