# Generated by Django 4.2.13 on 2024-12-05 13:51

import apps.doorlockdb.models
from django.db import migrations, models

import json


def move_meta_data_json(apps, schema_editor):
    # UnknownKey.meta_data_json ==> KeyMetaData.meta_data_json (using merge)
    # Key.meta_data_json ==> KeyMetaData.meta_data_json (using merge)
    #

    # We can't import the our models directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Key = apps.get_model("doorlockdb", "Key")
    LogUnknownKey = apps.get_model("doorlockdb", "LogUnknownKey")
    KeyMetaData = apps.get_model("doorlockdb", "KeyMetaData")

    for k in LogUnknownKey.objects.all():
        if k.meta_data_json != "{}":
            md, created = KeyMetaData.objects.get_or_create(hwid=k.hwid)
            meta_data = {
                **json.loads(md.meta_data_json),
                **json.loads(k.meta_data_json),
            }
            md.meta_data_json = json.dumps(meta_data, indent=4)
            md.save()

    for k in Key.objects.all():
        if k.meta_data_json != "{}":
            md, created = KeyMetaData.objects.get_or_create(hwid=k.hwid)
            meta_data = {
                **json.loads(md.meta_data_json),
                **json.loads(k.meta_data_json),
            }
            md.meta_data_json = json.dumps(meta_data, indent=4)
            md.save()


class Migration(migrations.Migration):

    dependencies = [
        ("doorlockdb", "0019_key_meta_data_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hwid", models.CharField(max_length=32, unique=True)),
                ("meta_data_json", models.TextField(default="{}")),
            ],
            bases=(apps.doorlockdb.models.AddKeyMetaDataModelMixin, models.Model),
        ),
        migrations.RunPython(move_meta_data_json),
        migrations.RemoveField(
            model_name="key",
            name="meta_data_json",
        ),
        migrations.RemoveField(
            model_name="logunknownkey",
            name="meta_data_json",
        ),
    ]
