# Generated by Django 4.2.17 on 2025-01-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doorlockdb", "0020_keymetadata_remove_key_meta_data_json_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LockWebsocketChannel",
            fields=[
                (
                    "lock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="doorlockdb.lock",
                    ),
                ),
                ("channel_name", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="lock",
            name="certificate",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Paste client certitificate here (including '-----BEGIN CERTIFICATE-----' and '-----END CERTIFICATE-----').<br>\n<br>\nOn the client configure this server server Fingerprint. (hint: restart django after server ssl certificate is changed). <br>\n<code>server_ssl_fingerprint='Error: [Errno 2] No such file or directory: '/etc/ssl/certs/ssl-cert-snakeoil.pem'. \n(see SERVER_SSL_CERTIFICATE in settings.py).'</code>",
                max_length=2000,
                null=True,
                unique=True,
            ),
        ),
    ]
