# Generated by Django 4.2.17 on 2025-01-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doorlockdb", "0021_lockwebsocketchannel_alter_lock_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="lockwebsocketchannel",
            name="short_name",
            field=models.CharField(
                default="2025-01-30 10:11:42.981347", max_length=64, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lockwebsocketchannel",
            name="channel_name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
