# Generated by Django 4.2.17 on 2025-01-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doorlockdb", "0022_lockwebsocketchannel_short_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lockwebsocketchannel",
            old_name="short_name",
            new_name="persistent_name",
        ),
        migrations.AlterField(
            model_name="lockwebsocketchannel",
            name="channel_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
