version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "4430:443"
    restart: "no"
    volumes:
     - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
     - ./config/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem:ro
     - ./config/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key:ro

#
# create SSL certificate:
#
# cd ./config/
# openssl req -subj '/CN=myhost.local' -x509 -newkey rsa:4096 -nodes -keyout ssl-cert-snakeoil.key -out ssl-cert-snakeoil.pem -days 365
#